# Generated by Django 3.1.1 on 2020-10-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metalfini', '0002_auto_20201004_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
