# Generated by Django 3.1.1 on 2020-10-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalfini', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/metalfini.appspot.com/o/metal.jpeg?alt=media&token=6eabb394-f737-4845-8d1c-857a7e927bf3'),
        ),
    ]
