# Generated by Django 3.1.1 on 2020-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalfini', '0005_auto_20201005_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='french_description',
            field=models.TextField(default='Description non disponible'),
        ),
        migrations.AddField(
            model_name='product',
            name='french_name',
            field=models.CharField(default='Nom du produit non disponible', max_length=220),
        ),
    ]
